---

INIT:
  DROOT: "./"
  FPATH_EXP: "expression_dataTuck_sub.csv"
  FPATH_TRJ: "pseudotimeTuck.txt"
  FPATH_BRANCH: "cell_selectTuck.txt"
  FPATH_TF: "mouse_tfs.txt"
  SPATH_RESULT: "TE_result_matrix.txt"
  MAKE_BINARY: True

BACKEND: "gpu"
DEVICE_IDS: 1
PROCS_PER_DEVICE: 1
BATCH_SIZE: 2**16

# you can select various discretizer by changing the BINNING_METHOD parameter including
# "FSBW", "FSBN", "FSBQ", "K-means"
# but we recommend using "FSBW-L" as it gives the most similar results to TENET
BINNING_METHOD: "FSBW-L"
KP: 0.5

# you can use smooth function by changing the SMOOTHING_OPT parameter
# the SMOOTHING_OPT parameter is optional and must be dictionary type (ex. {'method': 'exp'})
# 'mov', 'savgol', 'exp', 'loess' method parameters are available.
SMOOTHING_OPT: None