---

INIT:
  DROOT: "./"
  FPATH_EXP: "skin_exp_data.csv"
  FPATH_TRJ: "skin_pseudotime.txt"
  FPATH_BRANCH: "skin_cellselect.txt"
  FPATH_TF: "human_tfs.txt"
  SPATH_RESULT: "TE_result_matrix.txt"
  MAKE_BINARY: True

BACKEND: "gpu"
DEVICE_IDS: 8
PROCS_PER_DEVICE: 4
BATCH_SIZE: 2**12

# you can select various discretizer by changing the METHOD parameter including
# "interpolation", "tag", "fix", "quantile", "kmeans", "log"
# but we recommend using "shift_left" as it gives the most similar results to TENET
METHOD: "FSBW-L"
NUM_KERNELS: 1
KP: 0.5
DT: 1

# you can use smooth function by changing the SMOOTHFAMILY parameter
# the SMOOTHFAMILY parameter is optional and must be dictionary type (ex. {'method': 'exp'})
# 'mov', 'savgol', 'exp', 'loess' method parameters are available.
SMOOTHFAMILY: None