---

INIT:
  DROOT: "./"
  FPATH_EXP: "skin_exp_data.csv"
  FPATH_TRJ: "skin_pseudotime.txt"
  FPATH_BRANCH: "skin_cellselect.txt"
  FPATH_TF: "human_tfs.txt"
  SPATH_RESULT: "TE_result_matrix.txt"
  MAKE_BINARY: True

BACKEND: "gpu"
DEVICE_IDS: [1,2,3]
PROCS_PER_DEVICE: 4
BATCH_SIZE: 2**12

METHOD: "shift_left"
NUM_KERNELS: 1
KP: 0.5
DT: 1